# Generated by Django 3.0.1 on 2019-12-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reveal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codes',
            name='sub',
            field=models.IntegerField(default=0),
        ),
    ]
